CREATE TABLE [dbo].[APPOINTMENT](
	[ApptID] [int] IDENTITY(1,1) NOT NULL,
	[ClientID] [int] NULL,
	[ApptDate] [datetime] NOT NULL,
 CONSTRAINT [PK__APPOINTMENT__014935CB] PRIMARY KEY CLUSTERED 
(
	[ApptID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)
GO
ALTER TABLE [dbo].[APPOINTMENT]  WITH CHECK ADD  CONSTRAINT [FK__APPOINTME__Clien__023D5A04] FOREIGN KEY([ClientID])
REFERENCES [dbo].[CLIENT] ([ClientID])