CREATE TABLE [dbo].[HOT_TUB](
	[TubID] [int] IDENTITY(1,1) NOT NULL,
	[TubType] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TubL] [decimal](10, 2) NULL,
	[TubW] [decimal](10, 2) NULL,
	[TubD] [decimal](10, 2) NULL,
	[TubV] [decimal](10, 2) NULL,
	[QuoteID] [int] NULL,
 CONSTRAINT [PK__HOT_TUB__0AD2A005] PRIMARY KEY CLUSTERED 
(
	[TubID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)
GO
ALTER TABLE [dbo].[HOT_TUB]  WITH CHECK ADD  CONSTRAINT [FK__HOT_TUB__QuoteID__0BC6C43E] FOREIGN KEY([QuoteID])
REFERENCES [dbo].[QUOTE] ([QuoteID])