CREATE TABLE [dbo].[LOGIN_CLIENT](
	[LoginID] [int] IDENTITY(1,1) NOT NULL,
	[ClientID] [int] NULL,
	[Password] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK__LOGIN_CLIENT__7E6CC920] PRIMARY KEY CLUSTERED 
(
	[LoginID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)
GO
ALTER TABLE [dbo].[LOGIN_CLIENT]  WITH CHECK ADD  CONSTRAINT [FK__LOGIN_CLI__Clien__7F60ED59] FOREIGN KEY([ClientID])
REFERENCES [dbo].[CLIENT] ([ClientID])