CREATE TABLE [dbo].[POOL](
	[PoolID] [int] IDENTITY(1,1) NOT NULL,
	[PoolL] [decimal](10, 2) NULL,
	[PoolW] [decimal](10, 2) NULL,
	[PoolD] [decimal](10, 2) NULL,
	[PoolV] [decimal](10, 2) NULL,
	[QuoteID] [int] NULL,
 CONSTRAINT [PK__POOL__07F6335A] PRIMARY KEY CLUSTERED 
(
	[PoolID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)
GO
ALTER TABLE [dbo].[POOL]  WITH CHECK ADD  CONSTRAINT [FK__POOL__QuoteID__08EA5793] FOREIGN KEY([QuoteID])
REFERENCES [dbo].[QUOTE] ([QuoteID])