CREATE TABLE [dbo].[QUOTE](
	[QuoteID] [int] IDENTITY(1,1) NOT NULL,
	[ClientID] [int] NULL,
	[TubCost] [money] NULL,
	[PoolCost] [money] NULL,
	[ApptID] [int] NULL,
 CONSTRAINT [PK__QUOTE__0425A276] PRIMARY KEY CLUSTERED 
(
	[QuoteID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)
GO
ALTER TABLE [dbo].[QUOTE]  WITH CHECK ADD  CONSTRAINT [FK__QUOTE__ApptID__060DEAE8] FOREIGN KEY([ApptID])
REFERENCES [dbo].[APPOINTMENT] ([ApptID])
GO
ALTER TABLE [dbo].[QUOTE]  WITH CHECK ADD  CONSTRAINT [FK__QUOTE__ClientID__0519C6AF] FOREIGN KEY([ClientID])
REFERENCES [dbo].[CLIENT] ([ClientID])